
import { OrderDataToExport, OrderStatus, ProductInfo, CustomerInfo } from '../model/OrderDataToExport';
import api from './apiService'

export interface PostOrderModel {
    sourceId: number,
    storeId?: number | undefined,
    customer: CustomerInfo,
    products: ProductInfo[],
    orderNumber: number,
    orderStoreNumber: string,
    profileSource: string,
    profileTarget: string,
    date: Date,
    original: any
}

export const postTargetOrder = async (order: PostOrderModel, targetKey: string) => {
    let result = await api.post(
        `/api/profile/${order.profileTarget}/order?accountSecret=${targetKey}`,
        ({

            numero: undefined, // don't set the order number, this is sequential
            sourceId: order.sourceId,
            numeroLoja: order.original.numeroLoja, // order number generated by shoope, ML, Amazon...
            data: order.original.data || new Date().toISOString().split('T')[0],
            dataSaida: order.original.dataSaida || undefined,
            dataPrevista: order.original.dataPrevista || undefined,
            contato: {
                id: order.customer.original.id,
                tipoPessoa: order.customer.original.tipoPessoa,
                numeroDocumento: order.customer.original.numeroDocumento,
                nome: order.customer.original.nome,
            },
            situacao: undefined, // set as default
            loja: order.storeId 
                ? {
                    id: order.storeId
                }
                : undefined,
            numeroPedidoCompra: order.original.numeroPedidoCompra || undefined,
            outrasDespesas: order.original.outrasDespesas || undefined,
            observacoes: order.original.observacoes || undefined,
            observacoesInternas: order.original.observacoesInternas || undefined,
            desconto: order.original.desconto || undefined,
            categoria: order.original.categoria || undefined,
            tributacao: order.original.tributacao || undefined,
            itens: order.products.map(item => ({
                codigo: item.code || undefined,
                unidade: item.original.unidade || undefined,
                quantidade: item.original.quantidade || 0,
                desconto: item.original.desconto || undefined,
                valor: item.original.valor || 0,
                aliquotaIPI: item.original.aliquotaIPI || undefined,
                descricao: item.description || '',
                descricaoDetalhada: undefined,
                produto: {
                    id: item.id
                },
                comissao: undefined
            })) || [],
            parcelas: order.original.parcelas || [],
            transporte: undefined,
            vendedor: undefined,
            intermediador: undefined,
            taxas: undefined
        }))
        .then(response => response.data)
        .then(data => ({
            success: true,
            error: undefined,
            data: data?.data,
        }))
        .catch(error => {
            console.error(error)
            return ({
                success: false,
                error: `Falha ao criar pedido '${order.orderNumber}'.`,
                data: undefined,
            });
        });

    return result;
}

export const getOrders = async (profile: string, key: string, date: Date | undefined = undefined): Promise<OrderDataToExport[]> => {
    let result = await api.get(`/api/profile/${profile}/order?accountSecret=${key}&initialDate=${date?.toISOString().split('T')[0]}`)
        .then(response => response.data)
        .then(data => {
            if (Array.isArray(data.data) === false) {
                throw new Error("Failed to get data.");
            }

            return data.data.map((x: any) => createOrderFromJson(x, profile, key));
        })
        .catch(error => {
            console.error(error)
            return [];
        });

    return result;
}

const getCustomer = async (profile: string, key: string, documentNumber: string): Promise<CustomerInfo | undefined> => {
    let result = await api.get(`/api/profile/${profile}/customer?accountSecret=${key}&documentNumber=${documentNumber}`)
        .then(response => response.data)
        .then(data => {
            if (Array.isArray(data.data) === false) {
                throw new Error("Failed to get data.");
            }

            if (data.data.length === 0) return undefined;

            return data.data.map((x: any) => {
                let p: CustomerInfo = {
                    code: x.codigo,
                    documentNumber: x.numeroDocumento,
                    id: x.id,
                    name: x.nome,
                    phone: x.telefone,
                    profile: profile,
                    original: x
                };

                return p;
            })[0];
        })
        .catch(error => {
            console.error(error)
            return [];
        });

    return result;
}

export const getProducts = async (profile: string, key: string): Promise<ProductInfo[]> => {
    let result = await api.get(`/api/profile/${profile}/product?accountSecret=${key}`)
        .then(response => response.data)
        .then(data => {
            if (Array.isArray(data.data) === false) {
                throw new Error("Failed to get data.");
            }

            return data.data.map((x: any) => {
                let p: ProductInfo = {
                    code: x.codigo,
                    description: x.nome,
                    id: x.id,
                    profile: profile,
                    stockQuantity: x.estoque?.saldoVirtualTotal,
                    value: x.preco,
                    original: x,
                };

                return p;
            });
        })
        .catch(error => {
            console.error(error)
            return [];
        });

    return result;
}

// Factory function to create OrderDataToExport instances
const createOrderFromJson = (jsonOrder: any, profile: string, key: string): OrderDataToExport => {

    if (!jsonOrder)
        throw new Error('Invalid object.')

    const order: OrderDataToExport = {
        status: OrderStatus.NotStartedYet,
        number: jsonOrder.numero,
        orderStoreNumber: jsonOrder.numeroLoja,
        id: jsonOrder.id,
        profile: profile || 'Unknown',
        date: new Date(jsonOrder.data),
        productsToExport: [],
        products: [], // You can map products here if available in JSON
        errors: [],
        warnings: [],
        success: [],
        customer: {
            id: jsonOrder.contato?.id,
            code: '',
            name: jsonOrder.contato?.nome,
            documentNumber: jsonOrder.contato?.numeroDocumento,
            phone: '',
            original: jsonOrder,
            profile: profile
        },
        totalPrice: jsonOrder.total || jsonOrder.totalProdutos,
        original: jsonOrder,

        resetStatus() {
            this.status = OrderStatus.NotStartedYet;
            this.errors = [];
            this.warnings = [];
            this.success = [];
        },

        // This method should check the follow scenarios
        // - When the product stock is less than the order -> So it can be exported
        // - If it was already uploaded, so the field 'data.transferInfo' will be not null
        // 
        async processStatus(products: ProductInfo[], productsToExport: ProductInfo[]): Promise<void> {
            try {
                await api.get(`/api/profile/${profile}/order/${this.id}?accountSecret=${key}`)
                    .then(response => response.data)
                    .then(data => {
                        if (data.transferInfo) {
                            this.status = OrderStatus.Exported;
                            return;
                        }

                        let itens = data.data.itens;
                        if (Array.isArray(itens) === false) {
                            this.status = OrderStatus.Error;
                            this.errors.push('Produtos não encontrados.')
                            return;
                        }

                        let productsFailedToMatch: any = [];

                        var productWithNoStock = itens.find((item: any) => {
                            let productFound = products.find(x => x.id === item.produto?.id);

                            if (!productFound) {
                                // very hard to happen this case, 
                                // Bling ensures to have just orders with existent products
                                productsFailedToMatch.push(item);
                                this.errors.push(`Produto ${item.descricao} não encontrado no Bling raiz.`);
                                return false;
                            }

                            console.debug(`Checking product ${productFound.code} - Stock quantity: ${productFound.stockQuantity} | Order product quantity: ${item.quantidade}`)
                            if (productFound.stockQuantity >= item.quantidade) {
                                return false;
                            }

                            return true;
                        });

                        if (productsFailedToMatch.length > 0) {
                            console.error('failed to match products.', productsFailedToMatch);
                            this.status = OrderStatus.Error;
                            return;
                        }

                        if (!productWithNoStock)
                        {
                            this.status = OrderStatus.StockEnouth
                            return;
                        }

                        itens.forEach((item: any) => {

                            let productFoundToExport = productsToExport.find(x => x.code === item.codigo);

                            if (!productFoundToExport) {
                                productsFailedToMatch.push(item);
                                this.errors.push(`Produto ${item.descricao}(${item.codigo}) não encontrado no Bling para exportação. Realize o cadastro do mesmo.`);
                                return;
                            }
                            this.products.push(item);
                            productFoundToExport.original = item;
                            this.productsToExport.push(productFoundToExport);
                        });

                        if (productsFailedToMatch.length > 0) {
                            console.error('failed to match products.', productsFailedToMatch);
                            this.status = OrderStatus.Error;
                            return;
                        }
                        
                        this.status = OrderStatus.CanBeExported;
                    })
                    .catch(error => {
                        console.error(`Failed to process order ${this.number}, Id: ${this.id}:`, error);
                        this.status = OrderStatus.Error
                    });
                    
                var data = await getCustomer(profile, key, this.customer.documentNumber);
                if (data) this.customer = data;
            } catch (error) {
                console.error(`Failed to process order ${this.number}, Id: ${this.id}:`, error);
                this.status = OrderStatus.Error
                this.errors.push(`Falha em processar pedido.`);
            }
        }
    };

    return order;
};

export const createCustomer = async (customer: CustomerInfo, profile: string, key: string) => {
    let result = await api.post(
        `/api/profile/${profile}/customer/create?accountSecret=${key}`,
        ({
            nome: customer.original.nome || '',
            codigo: customer.original.codigo || undefined,
            situacao: "A",
            numeroDocumento: customer.documentNumber || undefined,
            telefone: customer.original.telefone || undefined,
            celular: customer.original.celular || undefined,
            fantasia: customer.original.fantasia || undefined,
            tipo: customer.original.tipo || '',
            indicadorIe: customer.original.indicadorIe || undefined,
            ie: customer.original.ie || undefined,
            rg: customer.original.rg || undefined,
            inscricaoMunicipal: customer.original.inscricaoMunicipal || undefined,
            orgaoEmissor: customer.original.orgaoEmissor || undefined,
            email: customer.original.email || undefined,
            emailNotaFiscal: customer.original.emailNotaFiscal || undefined,
            endereco: customer.original.endereco || undefined,
            vendedor: customer.original.vendedor || undefined,
            dadosAdicionais: customer.original.dadosAdicionais || undefined,
            financeiro: customer.original.financeiro || undefined,
            pais: customer.original.pais || undefined,
            tiposContato: customer.original.tiposContato || [],
            pessoasContato: customer.original.pessoasContato || []
        }))
        .then(response => response.data)
        .then(data => ({
            success: true,
            error: undefined,
            data: data?.data,
        }))
        .catch(error => {
            console.error(error)
            return ({
                success: false,
                error: `Falha ao criar/coletar cliente '${customer.documentNumber}'.`,
                data: undefined,
            });
        });

    return result;
}